#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

cd src; ./Allwmake; cd -;
cd solver; ./Allwmake; cd -;

echo Did you apply patch.liquid?

#------------------------------------------------------------------------------
