#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -r processor* constant/polyMesh log* 0 [0-9]* 
echo Case cleaned
cp -r save 0
echo Folder 0 initialized

#------------------------------------------------------------------------------
