#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


./Allclean

runApplication blockMesh

runApplication -s 1 mirrorMesh -dict system/mirrorMeshDict1 -overwrite
runApplication -s 2 mirrorMesh -dict system/mirrorMeshDict2 -overwrite

# Create ignition cells cellSet
# runApplication topoSet # AC maybe deactivate for now

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
